services:

    # PHP container
    app:
        build: ./app/
        container_name: php-app
        ports:
          - "8000:80"

    # MySQL database service
    app-db:
        build: ./database/
        image: mysql
        restart: always
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: "hive"   
        ports:
          - '3306:3306'
        expose:
        - '3306'

    # Jenkins container
    jenkins:
      build: ./jenkins/
      image: jenkins
      ports:
        - "8080:8080"

    # SonarQube Container
    sonarqube:
      
      image: sonarqube:community
      ports:
        - "9000:9000"