services:

    # PHP container
    app:
        build: ./app/
        container_name: php-app
        ports:
          - "8000:80"

    # MySQL database service
    app-db:
        build: ./database/
        image: mysql
        restart: always
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: "hive"   
        ports:
          - '3306:3306'
        expose:
        - '3306'

    # Jenkins container
    jenkins:
      build: ./jenkins/
      image: jenkins
      ports:
        - "8080:8080"
      networks:
        - jenkins
      volumes:
        - jenkins_data:/var/jenkins_home

    # SonarQube Container
    sonarqube:
      image: sonarqube:latest
      container_name: sonarqube
      environment:
        - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      ports:
        - "9000:9000"
      networks:
        - jenkins
      volumes:
        - sonarqube_data:/opt/sonarqube/data

networks:
  jenkins:
    driver: bridge

volumes:
  sonarqube_data:
  jenkins_data: