pipeline{
    agent any
    
    stages{
        stage('Clone the repo'){
            steps{
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'composer install'
            }
        }
        
        stage('Run PHPUnit tests') {
            steps {
                script {
                    sh 'vendor/bin/phpunit app/tests/.'
                }
            }
        }

        stage('SonarQube') {
            steps {
                script { scannerHome = tool 'SonarQube Scanner' }
                withSonarQubeEnv('SonarQube') {
                    sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=sonarqubetes1"
                }
            }
        }
    }
}