pipeline{
    agent any
    stages{
        stage('Clone the repo'){
            steps{
                checkout scm
            }
        }
        stage('PHPUnit tests') {
            agent{
                docker{
                    image 'composer:lts'
                }
            }
            steps {
                script {
                        sh 'composer install'
                        sh 'vendor/bin/phpunit app/.'
                    }
                }    
            }   
        stage('SonarQube') {
            steps {
                script { scannerHome = tool 'SonarQube Scanner' }
                withSonarQubeEnv('SonarQube') {
                    sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=sonarqubetes1"
                }
            }
        }
    }
}